blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :posts  

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/models/Post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  # validations go here
end

blog/app/models/User.rb
class User < ApplicationRecord
  has_secure_password

  has_many :posts
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = 1 #<-- don't do this 

    if @post.save
      respond_to  do |format|
        format.html { redirect_to @post }
        format.js
      end
    else
      render :new
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

blog/app/views/posts/create.js.erb
console.log('title', '<%= @post.title %>');

$('body').append('<h1><%= @post.title %></h1>');

blog/app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<%= link_to post.title, post_path(post) %>
<% end %>

<%= link_to "Add post", new_post_path %>

blog/app/views/posts/new.html.erb
<%= form_for @post, remote: true do |f| %>
	<p>
	<%= f.label :title %>
	<%= f.text_field :title %>
	</p>
	<p>
	<%= f.label :body %>
	<%= f.text_area :body %>
	</p>

	<%= f.submit %>
<% end %>

blog/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.body %></p>

blog/app/views/welcome/index.html.erb
<h1>Hello world!</h1>
<p>This is a breakout</p>